services:
  5oclock:
    image: 5oclock:user
    container_name: 5oclock_user
    ports:
      - "8000:8000"
    environment:
      - POP_LIMIT=15000
      - TARGET_24H=17
      - UID=1000
      - GID=999
    volumes:
      # Using Named Volumes instead of relative paths
      - geonames_data:/app/geonames
      - output_data:/app/output
      # for development only
      # - ./src:/app/src 
      # - ./templates:/app/templates
    restart: unless-stopped

# Declaring the named volumes
volumes:
  geonames_data:
  output_data: